### ISSUE TITLE
thoughts on hiding config.js (and mailgun dependency)

### ISSUE THREAD

**Issue by joates** [squatconf/website#13]
the app just won't start without configuration of some settings which are not sensitive, that makes it much harder for others to contribute (because not everyone has a mailgun account, or wants to go through the signup just to get a key so they can hack on the app), this is a big concern for me.. we never want to raise the barrier to contribution, always strive to lower it, ```npm install && npm start``` is accessible to everyone !!

also the config settings are undocumented, its just a file that you don't get, and you have to guess what goes in there in order to start the app, thats a huge anti-pattern IMO :(

so we need to de-couple the mailgun config (_essentially just the secret key part_) from general app config and when mailgun key is missing just bypass the mailgun functionality.

**Comment by gorhgorh** [comment]
no used anymore
