### ISSUE TITLE
Cleanup !

### ISSUE THREAD

**Issue by gorhgorh** [squatconf/website#17]
@joates I added a new branch,  [release/1.2.0](https://github.com/squatconf/website/tree/release/1.2.0)  where i switched the system to save emails a link to squatconf mailing list, I also removed the mailgun part. can you clean up the source dir so i don't erase things you intended to keep ? 

My plan is to make the site a static one for now served by nginx directly.

please close this issue when you are done, and I'll update the main ws

**Comment by joates** [comment]
> can you clean up the source dir so i don't erase things you intended to keep ?

sure thing, i'll take a look tomorrow.

> My plan is to make the site a static one for now served by nginx directly.

@gorhgorh 
good plan, should be a lot easier to maintain in the future.

**Comment by gorhgorh** [comment]
switched to static site with nginx done and pushed ws to version 1.2 in 969b0707b47d0afd5af168620ee60397feb29bee
