### ISSUE TITLE
Logo 2016

### ISSUE THREAD

**Issue by dignifiedquire** [squatconf/website#25]
I did some work based on the ideas from @gorhgorh and came up with the below:

![logo-2016-berlin](https://cloud.githubusercontent.com/assets/790842/13567414/74f6bc92-e45b-11e5-9a6c-62b04dfd6954.png)

**Comment by gorhgorh** [comment]
![berliner bear](https://cldup.com/f2Ob0phLxk.thumb.jpg)
![branderburg](http://imgur.com/VyxhWVy)

**Comment by ralphtheninja** [comment]
Nice!

**Comment by almereyda** [comment]
Thanks for taking a less power-laden representative monument as a symbol in https://github.com/squatconf/website/commit/0482f998b9f0ae10b7e71068b1819a52bb001481#diff-49e1f652ea286b6671c3e299e90aa3d3R122, even though it is closely related with the fall of the wall.
